# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100, verbose_name='\u95ee\u9898')),
                ('answer', models.TextField(default='', max_length=500, verbose_name='\u56de\u7b54')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq/%Y/%m', verbose_name='\u95ee\u7b54\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u95ee\u7b54',
                'verbose_name_plural': '\u95ee\u7b54',
            },
        ),
    ]
